tcsRoles=[

"DUP-TCS-Cross Functional Management",
"DUP-TCS-SAP-Support",
"DUP-TCS-APPS-Logical DBA",
"DUP-TCS-Collab-Apps Support",
"DUP-TCS-SAP-Vendavo",
"DUP-TCS-Technology-MW",
"DUP-TCS-Technology-TMB",
"DUP-TCS-SAP-Abap",
"DUP-TCS-SAP-Appmgt-BPC",
"DUP-TCS-SAP-Appmgt-CRM",
"DUP-TCS-SAP-Appmgt-EH&S",
"DUP-TCS-SAP-Appmgt-Esourcing",
"DUP-TCS-SAP-Appmgt-FIN",
"DUP-TCS-SAP-Appmgt-GTS",
"DUP-TCS-SAP-Appmgt-HR",
"DUP-TCS-SAP-Appmgt-MFG",
"DUP-TCS-SAP-Appmgt-PM",
"DUP-TCS-SAP-Appmgt-QM",
"DUP-TCS-SAP-Appmgt-RTP",
"DUP-TCS-SAP-Appmgt-SRM",
"DUP-TCS-SAP-Appmgt-STC",
"DUP-TCS-SAP-Appmgt-WM",
"DUP-TCS-SAP-Archive",
"DUP-TCS-SAP-BOBJ-Support",
"DUP-TCS-SAP-BP-Support",
"DUP-TCS-SAP-BW-Support",
"DUP-TCS-SAP-EUR-ABAP",
"DUP-TCS-SAP-PI/PO",
"DUP-TCS-SAP-Prometheus",
"DUP-TCS-SAP-Technology-Basis",
"DUP-TCS-SAP-Technology-Batch",
"DUP-TCS-SAP-Technology-BITools",
"DUP-TCS-SAP-Technology-DBA",
"DUP-TCS-SAP-Technology-ENV-CO",
"DUP-TCS-SAP-Technology-EUR Basis",
"DUP-TCS-SAP-Technology-Security",
"DUP-TCS-Finance-Apps",
"DUP-TCS-IFS",
"DUP-TCS-Java",
"DUP-TCS-SAP-ETL-Support",
"DUP-TCS-SAP-Meridium",
"DUP-TCS-SAP-MFTg App Support",
"DUP-TCS-SAP-Sales App Support",
"DUP-TCS-SAP-Technology-ARIS",
"DUP-TCS-SAP-Technology-eConnect",
"DUP-TCS-Technology App Support",
"DUP-TCS-Apps-MFG",
"DUP-TCS-Apps-MFG-Operations Discipline",
"DUP-TCS-Apps-MFG-Production Ops",
"DUP-TCS-Apps-MFG-Quality Ops",
"DUP-TCS-ECommerce Center",
"DUP-TCS-MFG-APPS SUPPORT-EQMS",
"DUP-TCS-INFRA-MIDDLEWARE",
"DUP-TCS-M&S-Apps Support",
"DUP-TCS-M&S-CQ-APP Support",
"DUP-TCS-MOB-Apps Support",
"DUP-TCS-LEGAL-Apps Support",
"DUP-TCS-FUNC-Apps Support",
"DUP-TCS-APPS-EBIZ",
"DUP-TCS-APPS-Oracle Transport Management",
"DUP-TCS-Apps-Output Management Services",
"DUP-TCS-Apps-Regional Support-LA",
"DUP-TCS-Security-EIS Operations",
"DUP-TCS-Security-Authentication"

]